repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["."]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    verbose: true
    hooks:
    -   id: mypy
    args: ["--ignore-missing-imports", "--show-error-codes", "--non-interactive"]
    additional_dependencies: ['types-PyYAML']
