#!/bin/bash
set -e # exit on error
set -x # echo commands
git fetch origin master
MINICONDA="Miniconda-$MINICONDA_VERSION-Linux-x86_64"
MINICONDA_URL="http://repo.continuum.io/miniconda/$MINICONDA.sh"
wget $MINICONDA_URL
bash $MINICONDA.sh -b -p $HOME/miniconda
rm -rf $MINICONDA.sh
python -V
PINNED_PKGS=$(cat <<EOF
scipy <0.15.0
EOF
)
echo -e "$PINNED_PKGS" > $HOME/miniconda/conda-meta/pinned
DEPS_TRAVIS="python=$TRAVIS_PYTHON_VERSION conda-build jinja2"
conda install --yes $DEPS_TRAVIS
conda config --add channels greole
CONDA_PY="${TRAVIS_PYTHON_VERSION/./}" conda build conda.recipe
conda install --use-local --yes owls
DEPS_TEST=$(cat <<EOF | python -
from conda_build.metadata import MetaData
print(" ".join([s.replace(" ", "") for s in MetaData("conda.recipe").get_value("test/requires")]))
)
